more defensive if dpkg-parsechangelog fails

diff --git a/debian/anon-base-files.postinst b/debian/anon-base-files.postinst
--- a/debian/anon-base-files.postinst
+++ b/debian/anon-base-files.postinst
@@ -31,16 +31,20 @@ case "$1" in
          if [ "$anon_dist_build_version" = "" ]; then
             ## Package dpkg-dev provides dpkg-parsechangelog.
             ## If anon_dist_build_version is empty, use the version number of the package.
-            anon_dist_build_version="$(zless "/usr/share/doc/$DPKG_MAINTSCRIPT_PACKAGE/changelog.Debian.gz" | dpkg-parsechangelog -l- -SVersion)"
+            anon_dist_build_version="$(zless "/usr/share/doc/$DPKG_MAINTSCRIPT_PACKAGE/changelog.Debian.gz" | dpkg-parsechangelog -l- -SVersion)" || true
          fi
-         mkdir --parents "$(dirname "$build_version_file")"
-         echo "INFO: Logging anon_dist_build_version $anon_dist_build_version to $build_version_file..."
-         ## Debugging.
-         touch "$build_version_file"
-         ## Logging.
-         echo "$anon_dist_build_version" > "$build_version_file"
-         ## Debugging.
-         cat "$build_version_file"
+         if [ "$anon_dist_build_version" = "" ]; then
+            echo "ERROR: Could not determine anon_dist_build_version."
+         else
+            mkdir --parents "$(dirname "$build_version_file")"
+            echo "INFO: Logging anon_dist_build_version $anon_dist_build_version to $build_version_file..."
+            ## Debugging.
+            touch "$build_version_file"
+            ## Logging.
+            echo "$anon_dist_build_version" > "$build_version_file"
+            ## Debugging.
+            cat "$build_version_file"
+         fi
       fi
 
       true 'INFO: Working around: "sudo: unable to resolve host host"'
