set default shell to `zsh` also for `root` user

diff --git a/debian/dist-base-files.postinst b/debian/dist-base-files.postinst
--- a/debian/dist-base-files.postinst
+++ b/debian/dist-base-files.postinst
@@ -239,7 +239,7 @@ zsh_yes_or_no() {
 }
 
 user_shell_to_zsh() {
-   if [ -f "/var/lib/dist-base-files/do_once/${FUNCNAME}_version_2" ]; then
+   if [ -f "/var/lib/dist-base-files/do_once/${FUNCNAME}_version_3" ]; then
       return 0
    fi
    mkdir --parents "/var/lib/dist-base-files/do_once"
@@ -248,29 +248,34 @@ user_shell_to_zsh() {
       return 0
    fi
 
-   if ! id "$user_to_be_created" &>/dev/null ; then
-      echo "$0: INFO: user '$user_to_be_created' does not exist. Not setting shell to zsh."
-      return 0
-   fi
+   local user_list user_list
+   user_list="root $user_to_be_created"
 
-   ## Use getent to retrieve the user's entry from /etc/passwd
-   user_passwd_entry=$(getent passwd "$user_to_be_created")
+   for user_item in $user_list ; do
+      if ! id "$user_item" &>/dev/null ; then
+         echo "$0: INFO: user '$user_item' does not exist. Not setting shell to zsh."
+         continue
+      fi
 
-   ## Extract the shell field (the last field) from the user's entry
-   user_default_shell=$(echo "$user_passwd_entry" | awk -F: '{print $NF}')
+      ## Use getent to retrieve the user's entry from /etc/passwd
+      user_passwd_entry=$(getent passwd "$user_item")
 
-   if [ "$user_default_shell" = "/usr/bin/zsh" ]; then
-      touch "/var/lib/dist-base-files/do_once/${FUNCNAME}_version_2"
-      return 0
-   fi
+      ## Extract the shell field (the last field) from the user's entry
+      user_default_shell=$(echo "$user_passwd_entry" | awk -F: '{print $NF}')
 
-   echo "$0: INFO: Setting shell for user '$user_to_be_created' to zsh."
-   if ! chsh --shell /usr/bin/zsh "$user_to_be_created" ; then
-      echo "$0: ERROR: Command 'chsh --shell /usr/bin/zsh user' failed. This is only a minor issue."
-   fi
-   echo "$0: INFO: For more information, see: https://www.kicksecure.com/shell#default"
+      if [ "$user_default_shell" = "/usr/bin/zsh" ]; then
+         touch "/var/lib/dist-base-files/do_once/${FUNCNAME}_version_3"
+         continue
+      fi
 
-   touch "/var/lib/dist-base-files/do_once/${FUNCNAME}_version_2"
+      echo "$0: INFO: Setting shell for user '$user_item' to zsh."
+      if ! chsh --shell /usr/bin/zsh "$user_item" ; then
+         echo "$0: ERROR: Command 'chsh --shell /usr/bin/zsh $user_item' failed. This is only a minor issue."
+      fi
+      echo "$0: INFO: For more information, see: https://www.kicksecure.com/shell#default"
+
+      touch "/var/lib/dist-base-files/do_once/${FUNCNAME}_version_3"
+   done
 }
 
 ## Define variables here to make this easier to software fork.
